### ISSUE TITLE
Optional option argument

### ISSUE THREAD

**Issue by naitian** [jedmao/gitlike-cli#4]
In the coercion example, the command argument is required, but the <code>-o</code> option has an optional argument. 

While <code>./coercion -o value file1.txt</code> works (and logs <code>options.optional: "value"</code>  and <code>args.file: ["file1.txt"]</code>), running <code>./coercion -o file1.txt</code> throws a "Missing required arguments" error, even though the optional option does not have a required argument.

Am I typing the command/arguments incorrectly or does the library not support this?

**Comment by jedmao** [comment]
I think [this is the test](https://github.com/jedmao/gitlike-cli/blob/master/test/Command.js#L117-L119) that covers that use case.

Can you show me your whole program?

**Comment by naitian** [comment]
Thanks for the quick response! I was looking at the coercion example in the examples directory. 

I think these are the two relevant blocks of code:

```javascript
program
  .usage('<files>...')
  .option('-s, --square <x>', 'A square of x', square)
  .option('-r, --range <a>..<b>', 'A range', range)
  .option('-l, --list <items>', 'A list', list)
  .option('-o, --optional [value]', 'An optional value')
  .parse(process.argv);

var options = program.options;
```
```javascript
console.log(' options.optional: %j', options.optional);
console.log(' args.files: %j', program.args.files);
```

**Comment by jedmao** [comment]
It looks like it could definitely be a bug. Can you submit a breaking test in the form of a pull request?

**Comment by naitian** [comment]
Sorry, but I am unsure of what you mean? Could you clarify or provide an example? Thanks!

**Comment by jedmao** [comment]
Have you submitted a pull request before?

**Comment by naitian** [comment]
Oh, yeah, I get the pull request part. It's writing the test that I'm not
familiar with.

**Comment by jedmao** [comment]
There are already tests in this project. All you would need to do is add a use-case where the test fails. Then, a commit could be added to fix that fail case.

**Comment by jedmao** [comment]
@naitian I'm going to close this issue for now, because you haven't provided a failing test case for what your expectations should be. Feel free to re-open if/when you decide to entertain this idea again.
